"""add message_store table

Revision ID: c485c259942f
Revises: c5e3c4291847
Create Date: 2025-03-09 17:47:07.705162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c485c259942f'
down_revision: Union[str, None] = 'c5e3c4291847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ia_message_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('score', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_answers') as batch_op:
        batch_op.alter_column('explanation',
                              existing_type=sa.String(),
                              nullable=False,
                              existing_nullable=True,
                              server_default='')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_answers') as batch_op:
        batch_op.alter_column('explanation',
                              existing_type=sa.String(),
                              nullable=True,
                              existing_nullable=False,
                              server_default=None)
    op.drop_table('ia_message_store')
    # ### end Alembic commands ###
