"""added explanation in answer table

Revision ID: c5e3c4291847
Revises: 6b4853fdc955
Create Date: 2025-02-25 10:48:50.480865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e3c4291847'
down_revision: Union[str, None] = '6b4853fdc955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_answers', sa.Column('explanation', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_answers', 'explanation')
    # ### end Alembic commands ###
